#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# ===============================================================
#  AK Software License v1.0
#  Copyright (c) 2025 AK (ak404z)
#
#  This software is provided for educational and research purposes
#  only. You are NOT allowed to use this code for:
#      - Illegal activities
#      - Harming individuals or organizations
#      - Unauthorized access or data breaches
#
#  By using this software, you agree that:
#      - The author is not responsible for any misuse.
#      - The tool is provided "AS IS" without any warranty.
#      - You assume full responsibility for any consequences.
#
#  You may modify and redistribute this code ONLY with proper
#  credit to the original author (AK / ak404z).
#
#  Unauthorized commercial use is strictly prohibited.
# ===============================================================
